
services:

  foton_cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: foton_cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    networks:
      - foton
  foton_postgres:
    container_name: foton_postgres
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-redmine}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-redmine}
      POSTGRES_DB: ${POSTGRES_DB:-redmine}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - foton

  foton_redmine:
    container_name: foton_redmine
    image: redmine:6.0
    depends_on:
      foton_postgres:
        condition: service_healthy
    ports:
      - "3123:3000"
    environment:
      REDMINE_DB_POSTGRES: foton_postgres
      REDMINE_DB_USERNAME: ${POSTGRES_USER:-redmine}
      REDMINE_DB_PASSWORD: ${POSTGRES_PASSWORD:-redmine}
      REDMINE_DB_DATABASE: ${POSTGRES_DB:-redmine}
      REDMINE_SMTP_ENABLED: "true"
      REDMINE_SMTP_HOST: ${SMTP_HOST:-smtp.example.com}
      REDMINE_SMTP_PORT: ${SMTP_PORT:-587}
      REDMINE_SMTP_USER: ${SMTP_USER:-email@example.com}
      REDMINE_SMTP_PASSWORD: ${SMTP_PASSWORD:-senhaEMAIL}
      REDMINE_SMTP_TLS: "true"
    volumes:      
      - ./redmine/plugins:/usr/src/redmine/plugins
      - ./redmine/themes:/usr/src/redmine/public/themes
      - ./redmine/config/configuration.yml:/usr/src/redmine/config/configuration.yml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    networks:
      - foton

# env_file:
#   - secrets/.secrets

volumes:
  redmine_postgres_data:
  redmine_data:

networks:
  foton:
    driver: bridge
    name: foton_network