# Generated by Django 4.2.3 on 2023-09-08 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fotonUser', '0002_organizacao_usuario_organizacao'),
        ('GestaoOrcamento', '0004_composicaocusto_orcamento_base_dados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composicaocusto',
            name='organizacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fotonUser.organizacao'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='organizacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fotonUser.organizacao'),
        ),
        migrations.AlterField(
            model_name='composicaocusto',
            name='descricao',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='base_dados',
            field=models.CharField(choices=[('SINAPI', 'SINAPI'), ('TCPO', 'TCPO'), ('GOINFRA', 'GOINFRA'), ('DNIT', 'DNIT'), ('FOTON', 'FOTON')], default='BASE', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='codigo_bim',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='descricao',
            field=models.TextField(default='DESCRICAO', null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='eficiencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
