# Generated by Django 4.2.3 on 2023-09-08 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fotonUser', '0003_alter_usuario_organizacao'),
        ('GestaoOrcamento', '0005_composicaocusto_organizacao_orcamento_organizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicaocusto',
            name='organizacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fotonUser.organizacao'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='organizacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fotonUser.organizacao'),
        ),
    ]
