type nul > .\base.html
type nul > .\home.html
type nul > .\contract_list.html
type nul > .\client_list.html
type nul > .\budget_list.html
type nul > .\login.html
type nul > .\user_dashboard.html
type nul > .\user_admin.html
type nul > .\system_admin.html