# Generated by Django 4.2.3 on 2023-09-08 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fotonUser', '0002_organizacao_usuario_organizacao'),
        ('GestaoContrato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='organizacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fotonUser.organizacao'),
        ),
    ]
