# Generated by Django 4.2.3 on 2023-09-08 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fotonUser', '0003_alter_usuario_organizacao'),
        ('GestaoContrato', '0002_contrato_organizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='organizacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fotonUser.organizacao'),
        ),
    ]
