default:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: smtp.hostinger.com
      port: 587
      domain: <%= ENV['REDMINE_SMTP_DOMAIN'] %>
      authentication: :login
      user_name: <%= ENV['REDMINE_SMTP_USER'] %>
      password: <%= ENV['REDMINE_SMTP_PASSWORD'] %>
      enable_starttls_auto: true
