default:
  delivery_method: :smtp
  smtp_settings:
    address: <%= ENV['SMTP_HOST'] %>
    port: <%= ENV['SMTP_PORT'] %>
    domain:  <%= ENV['SMTP_DOMAIN'] %>     
    authentivation: <%= ENV['SMTP_AUTH'] %>
    user_name: <%= ENV['SMTP_USER'] %>
    password: <%= ENV['SMTP_PASSWORD'] %>
    