# Generated by Django 4.2.3 on 2023-07-18 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_orcamento', '0001_initial'),
        ('gestao_cliente', '0002_cliente_contrato'),
        ('gestao_contrato', '0001_initial'),
    ]

    operations = [

    ]
'''
        migrations.AddField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='n_contrato', to='gestao_cliente.cliente'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='orcamento',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_contrato', to='gestao_orcamento.orcamento'),
        ),'''