# Generated by Django 4.2.3 on 2023-07-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_contrato', '0002_contrato_cliente_contrato_numero_contrato_orcamento'),
    ]

    operations = [

    ]
'''
        migrations(
            model_name='contrato',
            name='numero',
            field=models.CharField(default=0, max_length=100),
        ),'''