# Generated by Django 4.2.3 on 2023-07-18 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_contrato', '0003_contrato_numero'),
    ]

    operations = [
    ]
