# Generated by Django 4.2.3 on 2023-07-18 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_contrato', '0004_auto_20230718_2026'),
    ]

    operations = [

    ]
    '''
        migrations.RemoveField(
        model_name='contrato',
        name='numero',
        )
        ,
        migrations.RemoveField(
        model_name='contrato',
        name='cliente',
        )
        '''