# Generated by Django 4.2.3 on 2023-07-19 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_cliente', '0002_cliente_contrato'),
        ('gestao_orcamento', '0002_orcamento_contrato'),
        ('gestao_contrato', '0006_contrato_cliente_contrato_numero_contrato_orcamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='gestao_cliente.cliente'),
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='orcamento',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contratado', to='gestao_orcamento.orcamento'),
        ),
    ]
