# Generated by Django 4.2.3 on 2023-07-18 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_contrato', '0002_contrato_cliente_contrato_numero_contrato_orcamento'),
        ('gestao_orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='contrato',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato', to='gestao_contrato.contrato'),
        ),
    ]
