# Generated by Django 4.2.3 on 2023-09-08 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fotonUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física / MEI'), ('PJ_PRIVADO', 'Pessoa Jurídica de direito privado'), ('PJ_INTERNO', 'Pessoa Jurídica de direito público interno'), ('PJ_EXTERNO', 'Pessoa Jurídica de direito público externo')], default='PF', max_length=10)),
                ('nome_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outra')], max_length=1, null=True)),
                ('emprego_ocupacao', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('ug', models.CharField(blank=True, max_length=10, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('natureza', models.CharField(blank=True, choices=[('ASSOCIACAO', 'Associação'), ('SOCIEDADE', 'Sociedade'), ('FUNDACAO', 'Fundação'), ('RELIGIOSA', 'Organização Religiosa'), ('PARTIDO_POLITICO', 'Partido Político'), ('EIRELI', 'Empresa Individual de Responsabilidade Limitada'), ('OUTRA', 'Outra')], max_length=20, null=True)),
                ('nome_representante', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf_representante', models.CharField(blank=True, max_length=14, null=True)),
                ('telefone_representante', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='organizacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fotonUser.organizacao'),
        ),
    ]
